If:
  PathMatch: .*\.c

CompileFlags:
  Add:
    - "-x"
    - "c"
    - "-Wall"
    - "-Wextra"
    - "-I/opt/local/include"
    - "-std=c17"

---

If:
  PathMatch: .*\.cpp

CompileFlags:
  Add:
    - "-x"
    - "c++"
    - "-Wall"
    - "-Wextra"
    - "-I/opt/local/include"
    - "-std=c++20"

---

If:
  PathMatch: .*\.m

CompileFlags:
  Add:
    - "-x"
    - "objective-c"
    - "-Wall"
    - "-Wextra"
    - "-I/opt/local/include"
    - "-std=c17"

---

If:
  PathMatch: [.*\.mm, .*\.h]

CompileFlags:
  Add:
    - "-x"
    - "objective-c++"
    - "-Wall"
    - "-Wextra"
    - "-I/opt/local/include"
    - "-std=c++20"

---

If:
  PathMatch: .*\.cu

CompileFlags:
  Add:
    - "-x"
    - "cuda"
    - "-Wall"
    - "-Wextra"
    - "-I/opt/local/include"
    - "-std=c++20"
    - "-ferror-limit=0"
    - "--cuda-gpu-arch=sm_90"
